version: "3.3"

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine3.14
    network_mode: host
    ports: [
      5432:5432
    ]
    volumes: 
      - $PWD/src/database/data:/var/lib/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
